name: syslog-blackbox

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: syslog-blackbox
  version: latest

instance_groups:
- name: tcp-server
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: tcp-server
    release: syslog-blackbox

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
